version: '2'

services:
  backend:
    build: backend
    network_mode: 'bridge'
    ports:
      - '8080'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    links:
      - redis
    depends_on:
      - redis
    volumes_from:
      - secrets
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=m.test.bi
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/
    command: nodemon --watch backend backend/index.js
    extra_hosts:
      - "www.dnt.local:10.200.10.1"
      - "a.test.bi:10.200.10.1"

  backend-native:
    build: backend
    network_mode: 'bridge'
    ports:
      - '8080'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    links:
      - redis
    depends_on:
      - redis
    volumes_from:
      - secrets
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development
      - IS_NATIVE=1
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=n.test.bi
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/
    command: nodemon --watch backend backend/index.js
    extra_hosts:
      - "www.dnt.local:10.200.10.1"
      - "a.test.bi:10.200.10.1"

  redis:
    image: redis:3
    network_mode: 'bridge'
    logging:
      options:
        max-size: "10k"

  webpack:
    build: frontend
    network_mode: 'bridge'
    ports:
      - '3000'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/frontend
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=a.test.bi
      - VIRTUAL_PORT=3000
    logging:
      options:
        max-size: "500k"
    command: nodemon --watch frontend/webpack.config.js --exec "npm run webpack:serve"

  secrets:
    image: turistforeningen/ratatoskr-secrets:v5
    network_mode: 'bridge'
    volumes:
      - /secrets
