# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
          name: authenticate with google service account
          command: |
            echo $GCLOUD_DOCKER_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      - checkout

      - setup_remote_docker

      - run:
          name: build ratatoskr-backend docker image and push to GCR
          command: |
            cd backend/
            TAG_SHA=backend-${CIRCLE_SHA1:0:9}
            TAG_LATEST=backend-latest
            gcloud auth configure-docker --quiet
            docker build -t ratatoskr .
            docker tag ratatoskr eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_SHA
            docker tag ratatoskr eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_LATEST

            docker push eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_SHA
            docker push eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_LATEST

      - run:
          name: build ratatoskr-assets docker image and push to GCR
          command: |
            cd frontend/
            TAG_SHA=assets-${CIRCLE_SHA1:0:9}
            TAG_LATEST=assets-latest
            gcloud auth configure-docker --quiet
            docker build -t ratatoskr .
            docker tag ratatoskr eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_SHA
            docker tag ratatoskr eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_LATEST

            docker push eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_SHA
            docker push eu.gcr.io/dnt-docker-registry-public/ratatoskr:$TAG_LATEST


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only: deploy-dev
